
// This file has been generated by the GUI designer. Do not modify.
namespace SchedulerSharp.Windows
{
	public partial class AboutDilog
	{
		private global::Gtk.VBox vbox4;

		private global::Gtk.Image image225;

		private global::Gtk.Label label4;

		private global::Gtk.Label label5;

		private global::Gtk.HSeparator hseparator5;

		private global::Gtk.Label label7;

		private global::Gtk.Label label6;

		private global::Gtk.HSeparator hseparator4;

		private global::Gtk.Label label8;

		private global::Gtk.Button button178;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget SchedulerSharp.Windows.AboutDilog
			this.Name = "SchedulerSharp.Windows.AboutDilog";
			this.Title = global::Mono.Unix.Catalog.GetString("Sobre Scheduler#");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource("SchedulerSharp.icon512.png");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowGrow = false;
			this.DefaultWidth = 320;
			this.DefaultHeight = 450;
			// Internal child SchedulerSharp.Windows.AboutDilog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.image225 = new global::Gtk.Image();
			this.image225.Name = "image225";
			this.image225.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("SchedulerSharp.Icons.icon127.png");
			this.vbox4.Add(this.image225);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.image225]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("<span size=\"x-large\"><b>Sheduler-Sharp 0.8b</b></span>");
			this.label4.UseMarkup = true;
			this.label4.Justify = ((global::Gtk.Justification)(2));
			this.vbox4.Add(this.label4);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label4]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Simulador de escalonamento de processos.\nEscrito em C# com interface grafica em G" +
					"TK.\nImplementação dos algoritmos de escalonamento\nFCFS, SJF com Preempção e Roun" +
					"d Robim");
			this.label5.Justify = ((global::Gtk.Justification)(2));
			this.vbox4.Add(this.label5);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label5]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hseparator5 = new global::Gtk.HSeparator();
			this.hseparator5.Name = "hseparator5";
			this.vbox4.Add(this.hseparator5);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hseparator5]));
			w5.Position = 3;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Copyright © 2019 Gabriela Faria de Oliveira");
			this.vbox4.Add(this.label7);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label7]));
			w6.Position = 4;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Copyright © 2019 Wilgnne Khawan Barbosa de Alencar");
			this.vbox4.Add(this.label6);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label6]));
			w7.Position = 5;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hseparator4 = new global::Gtk.HSeparator();
			this.hseparator4.Name = "hseparator4";
			this.vbox4.Add(this.hseparator4);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hseparator4]));
			w8.Position = 6;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("<span foreground=\"red\"><u>www.github.com/Wilgnne/Scheduler-Sharp</u></span>");
			this.label8.UseMarkup = true;
			this.label8.Selectable = true;
			this.vbox4.Add(this.label8);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label8]));
			w9.Position = 7;
			w9.Expand = false;
			w9.Fill = false;
			w1.Add(this.vbox4);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(w1[this.vbox4]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Internal child SchedulerSharp.Windows.AboutDilog.ActionArea
			global::Gtk.HButtonBox w11 = this.ActionArea;
			w11.Name = "__gtksharp_167_Stetic_TopLevelDialog_ActionArea";
			w11.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child __gtksharp_167_Stetic_TopLevelDialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.button178 = new global::Gtk.Button();
			this.button178.CanFocus = true;
			this.button178.Name = "button178";
			this.button178.UseStock = true;
			this.button178.UseUnderline = true;
			this.button178.Label = "gtk-close";
			this.AddActionWidget(this.button178, -7);
			global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w11[this.button178]));
			w12.Expand = false;
			w12.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Show();
			this.button178.Clicked += new global::System.EventHandler(this.CloseEvent);
		}
	}
}
